### ISSUE TITLE
Wrong response is returned when rate limit exceeds

### ISSUE THREAD

**Issue by MRiverRed** [Southclaws/swirl#1]
https://github.com/Southclaws/sliding-window-counters/blob/1cc00c9d7825a37dd89a6b0b22e87f155d9b10b0/ratelimit/middleware.go#L59-L77

Consider a scenario in which Increment(ctx, key, weight) returns a non-nil error.
There's no code path that leads to the error being written into the response and return to the customer.

@Southclaws if you're cool with the I can create a PR a fix it.

**Comment by Southclaws** [comment]
Good catch, yes that would be amazing if you opened a PR, thank you!

**Comment by MRiverRed** [comment]
@Southclaws no problem! Can you please grant me permissions to push new branches to upstream as well as create PRs?

**Comment by Southclaws** [comment]
You should have access to create PRs.

**Comment by Southclaws** [comment]
Solved in v1.0.0
