### ISSUE TITLE
sliding logs reset when redis is expired

### ISSUE THREAD

**Issue by BananZG** [Southclaws/swirl#2]
In redis/redis.go's Increment function, the redis is set to expired with `limitPeriod`.
This means that between end of limit period and start of next period, there could be rate exceeded cases as the last window is cleared.

For example:
- limitPeriod 1h
- counterWindow 1m
- limit: 10

at 0:00, call Increment once, cache created.
at 0:59, call Increment 8 times, no error.
at 1:01, cache reset, able to call Increment 9 times.

Should we extend redis expire?

**Comment by Southclaws** [comment]
Makes sense, thanks for raising this!
